name: Pipeline CI/CD - Déploiement Infrastructure et cv

on:
  push:
      branches:
        - main

jobs:
    deploy-infra:
       runs-on : ubuntu-latest

       steps:
       - name : Récupérer le code du dépot 
         uses : actions/checkout@v4

       - name : Configuration Terraform
         uses : hashicorp/setup-terraform@v3
  
       - name : Configurer les identifiants AWS
         uses : aws-actions/configure-aws-credentials@v4
         with :
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-3

       - name : Terraform Init
         run  : terraform init

       - name : Terraform Apply
         run  : terraform apply -auto-approve 